{
    "version": "3",
    "volumes": {
        "notebook-postgres-data": {}
    },
    "services": {
        "postgres": {
            "image": "postgres:9.6-alpine",
            "environment": {
                "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD:-postgres}"
            },
            "volumes": [
                "notebook-postgres-data:/var/lib/postgresql/data/",
                "./initdb/:/docker-entrypoint-initdb.d/"
            ],
            "ports": [
                "${POSTGRES_PORT:-5454}:5432"
            ]
        },
        "php-apache": {
            "build": {
                "context": "./",
                "dockerfile": "Dockerfile"
            },
            "volumes": [
                "./:/var/www/"
            ],
            "ports": [
                "${APACHE_PORT:-8080}:80"
            ],
            "depends_on": [
                "postgres"
            ]
        }
    }
}
